#include <FastLED.h>

FASTLED_USING_NAMESPACE

#if defined(FASTLED_VERSION) && (FASTLED_VERSION < 3001000)
#warning "Requires FastLED 3.1 or later; check github for latest code."
#endif

#define DATA_PIN    6
#define LED_TYPE    WS2811
#define COLOR_ORDER GRB
#define NUM_LEDS    300
CRGB leds[NUM_LEDS];

#define BRIGHTNESS          255 //0-255, use > 50 when driven from Arduino
#define FRAMES_PER_SECOND  240

void setup() {
  pinMode(3, INPUT); //PIR sensor
  delay(100); // 3 second delay for recovery
  
  // tell FastLED about the LED strip configuration
  FastLED.addLeds<LED_TYPE,DATA_PIN,COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);

  // set master brightness control
  FastLED.setBrightness(BRIGHTNESS);
}

// List of patterns to cycle through.  Each is defined as a separate function below.
typedef void (*SimplePatternList[])();
SimplePatternList gPatterns = { confetti, sinelon, juggle };

uint8_t gCurrentPatternNumber = 0; // Index number of which pattern is current
uint8_t gHue = 0; // rotating "base color" used by many of the patterns


//#####  Color Palette by Paletton.com
//#####  Palette URL: http://paletton.com/#uid=30s0u0kpOGxckTcjPMbA4BXACnV
//
//
//*** Primary color:
//
//   shade 0 = #FF8B31 = rgb(255,139, 49) = rgba(255,139, 49,1) = rgb0(1,0.545,0.192)
//   shade 1 = #FFC79D = rgb(255,199,157) = rgba(255,199,157,1) = rgb0(1,0.78,0.616)
//   shade 2 = #FFA661 = rgb(255,166, 97) = rgba(255,166, 97,1) = rgb0(1,0.651,0.38)
//   shade 3 = #FF6F00 = rgb(255,111,  0) = rgba(255,111,  0,1) = rgb0(1,0.435,0)
//   shade 4 = #BF5300 = rgb(191, 83,  0) = rgba(191, 83,  0,1) = rgb0(0.749,0.325,0)
//
//*** Secondary color (1):
//
//   shade 0 = #3DE12C = rgb( 61,225, 44) = rgba( 61,225, 44,1) = rgb0(0.239,0.882,0.173)
//   shade 1 = #9FF496 = rgb(159,244,150) = rgba(159,244,150,1) = rgb0(0.624,0.957,0.588)
//   shade 2 = #67EA59 = rgb(103,234, 89) = rgba(103,234, 89,1) = rgb0(0.404,0.918,0.349)
//   shade 3 = #15DB00 = rgb( 21,219,  0) = rgba( 21,219,  0,1) = rgb0(0.082,0.859,0)
//   shade 4 = #0F9C00 = rgb( 15,156,  0) = rgba( 15,156,  0,1) = rgb0(0.059,0.612,0)
//
//*** Secondary color (2):
//
//   shade 0 = #3768C9 = rgb( 55,104,201) = rgba( 55,104,201,1) = rgb0(0.216,0.408,0.788)
//   shade 1 = #99B4EA = rgb(153,180,234) = rgba(153,180,234,1) = rgb0(0.6,0.706,0.918)
//   shade 2 = #5F88D8 = rgb( 95,136,216) = rgba( 95,136,216,1) = rgb0(0.373,0.533,0.847)
//   shade 3 = #104ABC = rgb( 16, 74,188) = rgba( 16, 74,188,1) = rgb0(0.063,0.29,0.737)
//   shade 4 = #0A327F = rgb( 10, 50,127) = rgba( 10, 50,127,1) = rgb0(0.039,0.196,0.498)
//
//
//#####  Generated by Paletton.com (c) 2002-2014

  
void loop()
{
  boolean pir = digitalRead(3); //Is there a person nearby?
  
  // Call the current pattern function once, updating the 'leds' array
  gPatterns[gCurrentPatternNumber]();

  // send the 'leds' array out to the actual LED strip
  FastLED.show();  
  // insert a delay to keep the framerate modest
  FastLED.delay(1000/FRAMES_PER_SECOND); 

  // do some periodic updates
  EVERY_N_MILLISECONDS( 10 ) { gHue++; } // slowly cycle the "base color" through the rainbow
  EVERY_N_SECONDS( 5 ) { nextPattern(); } // change patterns periodically

//  if(pir == HIGH){
//    nextPattern();
//  }
}

#define ARRAY_SIZE(A) (sizeof(A) / sizeof((A)[0]))

void nextPattern()
{
  // add one to the current pattern number, and wrap around at the end
  gCurrentPatternNumber = (gCurrentPatternNumber + 1) % ARRAY_SIZE( gPatterns);
}

void confetti() 
{
  // random colored speckles that blink in and fade smoothly
  fadeToBlackBy( leds, NUM_LEDS, 10);
  int pos = random16(NUM_LEDS);
  leds[pos] += CHSV( gHue + random8(64), 200, 255);
}

void sinelon()
{
  // a colored dot sweeping back and forth, with fading trails
  fadeToBlackBy( leds, NUM_LEDS, 20);
  int pos = beatsin16( 13, 0, NUM_LEDS-1 );
  leds[pos] += CHSV( gHue, 255, 192);
}

void juggle() {
  // eight colored dots, weaving in and out of sync with each other
  fadeToBlackBy( leds, NUM_LEDS, 20);
  byte dothue = 0;
  for( int i = 0; i < 8; i++) {
    leds[beatsin16( i+7, 0, NUM_LEDS-1 )] |= CHSV(dothue, 200, 255);
    dothue += 32;
  }
}
